# Generated by Django 5.1.4 on 2024-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0003_companydetailsmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailsmodel',
            name='shops_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/companylogo'),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyemployeedetailsmodel',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyemployeedetailsmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companyemployeedetailsmodel',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
