# Generated by Django 5.1.4 on 2025-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0005_alter_companydetailsmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailsmodel',
            name='company_registration_document',
            field=models.FileField(null=True, upload_to='company_registration_doc/'),
        ),
        migrations.AddField(
            model_name='companydetailsmodel',
            name='merchant_type',
            field=models.CharField(choices=[('freelance', 'Freelance'), ('shop', 'Shop')], default='freelance', max_length=20),
        ),
        migrations.AddField(
            model_name='companydetailsmodel',
            name='name_arabic',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='companydetailsmodel',
            name='tax_registration_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
