# Generated by Django 5.1.4 on 2025-02-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0006_companydetailsmodel_company_registration_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='company_registration_document',
            field=models.FileField(blank=True, null=True, upload_to='company_registration_doc/'),
        ),
    ]
