# Generated by Django 5.1.4 on 2025-02-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0008_remove_companyemployeedetailsmodel_company_and_more'),
        ('shopApp', '0011_alter_shopspecialistdetailsmodel_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyemployeerolemanagementmodel',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='companyemployeerolemanagementmodel',
            name='shop',
        ),
        migrations.DeleteModel(
            name='CompanyEmployeeDetailsModel',
        ),
        migrations.DeleteModel(
            name='CompanyEmployeeRoleManagementModel',
        ),
    ]
