# Generated by Django 5.1.4 on 2025-04-08 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0009_remove_companyemployeerolemanagementmodel_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetailsmodel',
            old_name='company_registration_document',
            new_name='registration_document',
        ),
        migrations.RenameField(
            model_name='companydetailsmodel',
            old_name='tax_registration_number',
            new_name='tax_number',
        ),
        migrations.AddField(
            model_name='companydetailsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Creation timestamp'),
        ),
        migrations.AddField(
            model_name='companydetailsmodel',
            name='forecast_data',
            field=models.JSONField(blank=True, help_text='AI forecast metadata', null=True),
        ),
        migrations.AddField(
            model_name='companydetailsmodel',
            name='fraud_flag',
            field=models.BooleanField(default=False, help_text='Flag if potential fraud detected'),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('created', 'Created')], default='created', max_length=30),
        ),
    ]
