# Generated by Django 5.1.4 on 2025-04-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0010_rename_company_registration_document_companydetailsmodel_registration_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetailsmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/companylogo/'),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='name_arabic',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='shops_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
