# Generated by Django 5.1.4 on 2025-04-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0012_alter_companydetailsmodel_forecast_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/companylogo'),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='forecast_data',
            field=models.JSONField(blank=True, default=dict, help_text='AI forecast metadata (must be pure JSON-serializable types)', null=True),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='name_arabic',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='shops_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='tax_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
