# Generated by Django 5.1.4 on 2025-04-09 14:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0013_alter_companydetailsmodel_company_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetailsmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='forecast_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='AI forecast metadata (will JSON‑encode datetimes/timestamps)', null=True),
        ),
    ]
