# Generated by Django 5.1.4 on 2025-04-10 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0014_alter_companydetailsmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydetailsmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='companydetailsmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AddIndex(
            model_name='companydetailsmodel',
            index=models.Index(fields=['name'], name='companyApp__name_0680ab_idx'),
        ),
        migrations.AddIndex(
            model_name='companydetailsmodel',
            index=models.Index(fields=['user'], name='companyApp__user_id_7af895_idx'),
        ),
    ]
