# Generated by Django 5.1.4 on 2025-04-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0015_alter_companydetailsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetailsmodel',
            name='online_payment_global_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, all shops for this company will be eligible for online payments.'),
        ),
    ]
