# Generated by Django 5.1.4 on 2025-02-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_alter_employeedetailsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinghoursmodel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='employeeApp.employeedetailsmodel'),
        ),
    ]
