# Generated by Django 5.1.4 on 2025-02-21 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_alter_employeeworkinghoursmodel_employee'),
        ('shopApp', '0011_alter_shopspecialistdetailsmodel_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetailsmodel',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='employeedetailsmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeRoleManangementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('can_edit_shop', models.BooleanField(default=False)),
                ('can_add_services', models.BooleanField(default=False)),
                ('can_edit_services', models.BooleanField(default=False)),
                ('can_add_employee', models.BooleanField(default=False)),
                ('can_edit_employee', models.BooleanField(default=False)),
                ('can_delete_employee', models.BooleanField(default=False)),
                ('can_add_specialist', models.BooleanField(default=False)),
                ('can_edit_specialist', models.BooleanField(default=False)),
                ('can_delete_specialist', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='employeeApp.employeedetailsmodel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='shopApp.shopdetailsmodel')),
            ],
            options={
                'unique_together': {('shop', 'employee')},
            },
        ),
    ]
