# Generated by Django 5.1.4 on 2025-04-13 04:59

import django.db.models.deletion
import employeeApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0009_alter_employeeworkinghoursmodel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetailsmodel',
            name='user',
            field=models.OneToOneField(default=employeeApp.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
