# Generated by Django 5.1.4 on 2025-04-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reelsApp', '0002_add_view_count_field'),
        ('reelsApp', '0003_add_analytics_text'),
    ]

    operations = [
    ]
