# Generated by Django 5.1.4 on 2025-04-12 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelsApp', '0005_rename_analytics_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelsmodel',
            name='analytics_data',
            field=models.JSONField(blank=True, help_text='Advanced analytics data', null=True),
        ),
        migrations.CreateModel(
            name='ReelsAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_watch_time', models.FloatField(default=0.0)),
                ('drop_off_rate', models.FloatField(default=0.0)),
                ('additional_data', models.JSONField(blank=True, help_text='Any additional analytics data', null=True)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='reelsApp.reelsmodel')),
            ],
        ),
    ]
