# Generated by Django 5.1.4 on 2025-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('payment_type', models.CharField(choices=[('p', 'Payment'), ('u', 'Upgrade')], max_length=1)),
                ('payed_for', models.CharField(choices=[('s', 'Subscription'), ('ad', 'Ad Service'), ('m', 'Merchant Payment')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_name', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
            ],
        ),
    ]
