# Generated by Django 5.1.4 on 2025-04-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payed_for',
            new_name='payment_for',
        ),
    ]
