# Generated by Django 5.1.4 on 2024-12-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_shopdetailsmodel_owner_shopgalleryimagesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
