# Generated by Django 5.1.4 on 2025-01-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0005_alter_companydetailsmodel_user'),
        ('shopApp', '0004_shopspecialistdetailsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopspecialistdetailsmodel',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='companyApp.companyemployeedetailsmodel'),
            preserve_default=False,
        ),
    ]
