# Generated by Django 5.1.4 on 2025-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_shopspecialistdetailsmodel_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='avatar_image',
            field=models.ImageField(default='', upload_to='images/shop/avatr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/shop/cover'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
