# Generated by Django 5.1.4 on 2025-01-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0006_shopdetailsmodel_avatar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='avatar_image',
            field=models.ImageField(upload_to='images/shopgallery/'),
        ),
    ]
