# Generated by Django 5.1.4 on 2025-02-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_shopdetailsmodel_categories_shopdetailsmodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/shopgallery/'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='shop_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
