# Generated by Django 5.1.4 on 2025-02-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_alter_shopdetailsmodel_avatar_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
