# Generated by Django 5.1.4 on 2025-02-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_alter_employeeworkinghoursmodel_employee'),
        ('shopApp', '0010_alter_shopdetailsmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='employeeApp.employeedetailsmodel'),
        ),
    ]
