# Generated by Django 5.1.4 on 2025-02-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0011_alter_shopspecialistdetailsmodel_employee'),
        ('shopServiceApp', '0012_remove_shopservicedetailsmodel_number_of_bookings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='shopspecialistdetailsmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='shopspecialistdetailsmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shopspecialistdetailsmodel',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='shopspecialistdetailsmodel',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='specialist/avatar_image/'),
        ),
        migrations.AddField(
            model_name='shopspecialistdetailsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopspecialistdetailsmodel',
            name='service_locatioin',
            field=models.CharField(choices=[('in_store', 'In Store'), ('at_shop', 'At Shop'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='shopspecialistdetailsmodel',
            name='services',
            field=models.ManyToManyField(to='shopServiceApp.shopservicedetailsmodel'),
        ),
        migrations.RemoveField(
            model_name='shopspecialistdetailsmodel',
            name='shop',
        ),
        migrations.AddField(
            model_name='shopspecialistdetailsmodel',
            name='specialist_type',
            field=models.ManyToManyField(to='shopApp.specialisttypesmodel'),
        ),
        migrations.AddField(
            model_name='shopspecialistdetailsmodel',
            name='shop',
            field=models.ManyToManyField(to='shopApp.shopdetailsmodel'),
        ),
    ]
