# Generated by Django 5.1.4 on 2025-03-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0012_specialisttypesmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Credits for ads and other things', max_digits=10),
        ),
    ]
