# Generated by Django 5.1.4 on 2025-04-08 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0013_shopdetailsmodel_credits'),
        ('shopServiceApp', '0016_servicebookingdetailsmodel_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopdetailsmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='ai_recommendations',
            field=models.JSONField(blank=True, help_text='AI recommendation metadata', null=True),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Creation date and time'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='shops', to='shopServiceApp.shopservicecategorymodel'),
        ),
    ]
