# Generated by Django 5.1.4 on 2025-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0014_alter_shopdetailsmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopspecialistdetailsmodel',
            old_name='service_locatioin',
            new_name='service_location',
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='customers_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='services_types',
            field=models.CharField(choices=[('in_shop', 'In Shop'), ('at_home', 'At Home'), ('both', 'Both')], default='in_shop', max_length=20),
        ),
    ]
