# Generated by Django 5.1.4 on 2025-04-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0015_rename_service_locatioin_shopspecialistdetailsmodel_service_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='ai_personalization',
            field=models.JSONField(blank=True, help_text='AI personalization metadata', null=True),
        ),
    ]
