# Generated by Django 5.1.4 on 2025-04-10 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0015_alter_companydetailsmodel_options_and_more'),
        ('shopApp', '0016_shopdetailsmodel_ai_personalization'),
        ('shopServiceApp', '0017_rename_is_availabe_shopservicedetailsmodel_is_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopdetailsmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='shopgalleryimagesmodel',
            options={'verbose_name': 'Shop Gallery Image', 'verbose_name_plural': 'Shop Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='shopopeninghoursmodel',
            options={'verbose_name': 'Shop Opening Hour', 'verbose_name_plural': 'Shop Opening Hours'},
        ),
        migrations.AlterModelOptions(
            name='shoppermissionsmodel',
            options={'verbose_name': 'Shop Permission', 'verbose_name_plural': 'Shop Permissions'},
        ),
        migrations.AlterModelOptions(
            name='shopspecialistdetailsmodel',
            options={'verbose_name': 'Shop Specialist Detail', 'verbose_name_plural': 'Shop Specialist Details'},
        ),
        migrations.AlterModelOptions(
            name='specialisttypesmodel',
            options={'verbose_name': 'Specialist Type', 'verbose_name_plural': 'Specialist Types'},
        ),
        migrations.RemoveField(
            model_name='shopspecialistdetailsmodel',
            name='employee',
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='ai_personalization',
            field=models.JSONField(blank=True, help_text='AI personalization metadata', null=True, verbose_name='AI Personalization'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='ai_recommendations',
            field=models.JSONField(blank=True, help_text='AI recommendation metadata', null=True, verbose_name='AI Recommendations'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/shopgallery/', verbose_name='Avatar Image'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='shops', to='shopServiceApp.shopservicecategorymodel', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailsmodel', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='images/shop/cover', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Creation timestamp', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Credits for ads and other activities', max_digits=10, verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='customers_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=20, verbose_name='Target Customers'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='district',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=300, unique=True, verbose_name='Unique Name'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='services_types',
            field=models.CharField(choices=[('in_shop', 'In Shop'), ('at_home', 'At Home'), ('both', 'Both')], default='in_shop', max_length=20, verbose_name='Services Types'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='shop_name',
            field=models.CharField(db_index=True, default='', max_length=300, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='shopdetailsmodel',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='shopgalleryimagesmodel',
            name='image',
            field=models.ImageField(upload_to='images/shopgallery', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='shopgalleryimagesmodel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopdetailsmodel', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='shopopeninghoursmodel',
            name='close_time',
            field=models.TimeField(verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='shopopeninghoursmodel',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, verbose_name='Day of Week'),
        ),
        migrations.AlterField(
            model_name='shopopeninghoursmodel',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='shopopeninghoursmodel',
            name='open_time',
            field=models.TimeField(verbose_name='Opening Time'),
        ),
        migrations.AlterField(
            model_name='shopopeninghoursmodel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='shopApp.shopdetailsmodel', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='shoppermissionsmodel',
            name='can_create_product',
            field=models.BooleanField(default=False, verbose_name='Can Create Product'),
        ),
        migrations.AlterField(
            model_name='shoppermissionsmodel',
            name='can_delete_product',
            field=models.BooleanField(default=False, verbose_name='Can Delete Product'),
        ),
        migrations.AlterField(
            model_name='shoppermissionsmodel',
            name='can_edit_product',
            field=models.BooleanField(default=False, verbose_name='Can Edit Product'),
        ),
        migrations.AlterField(
            model_name='shoppermissionsmodel',
            name='can_view_product',
            field=models.BooleanField(default=True, verbose_name='Can View Product'),
        ),
        migrations.AlterField(
            model_name='shoppermissionsmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailsmodel', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='shoppermissionsmodel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopdetailsmodel', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='specialist/avatar_image/', verbose_name='Avatar Image'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='service_location',
            field=models.CharField(choices=[('in_store', 'In Store'), ('at_shop', 'At Shop'), ('both', 'Both')], default='both', max_length=20, verbose_name='Service Location'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='services',
            field=models.ManyToManyField(to='shopServiceApp.shopservicedetailsmodel', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='shop',
            field=models.ManyToManyField(to='shopApp.shopdetailsmodel', verbose_name='Shops'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='specialist_type',
            field=models.ManyToManyField(to='shopApp.specialisttypesmodel', verbose_name='Specialist Type'),
        ),
        migrations.AlterField(
            model_name='shopspecialistdetailsmodel',
            name='speciality',
            field=models.CharField(max_length=300, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='specialisttypesmodel',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='shopopeninghoursmodel',
            index=models.Index(fields=['day'], name='shopApp_sho_day_ee8b5e_idx'),
        ),
    ]
