# Generated by Django 5.1.4 on 2025-04-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0017_alter_shopdetailsmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='bank_details_document',
            field=models.FileField(blank=True, null=True, upload_to='bank_details/', verbose_name='Bank Details Document'),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='online_payment_requested',
            field=models.BooleanField(default=False, verbose_name='Receive Online Payments'),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='online_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Online Payment Approval Status'),
        ),
    ]
