# Generated by Django 5.1.4 on 2025-04-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0018_shopdetailsmodel_bank_details_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopPermissionsModel',
        ),
    ]
