# Generated by Django 5.1.4 on 2025-04-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0019_delete_shoppermissionsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopdetailsmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='shopdetailsmodel',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='shopdetailsmodel',
            name='credits',
        ),
    ]
