# Generated by Django 5.1.4 on 2025-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0020_alter_shopdetailsmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdetailsmodel',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='customer_service_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Customer Service Phone'),
        ),
        migrations.AddField(
            model_name='shopdetailsmodel',
            name='manager_phone_number',
            field=models.CharField(help_text='Manager Phone Number (used for branch login)', max_length=20, null=True, unique=True),
        ),
    ]
