# Generated by Django 5.1.4 on 2025-03-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0001_initial'),
        ('shopApp', '0013_shopdetailsmodel_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadsmodel',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopdetailsmodel'),
            preserve_default=False,
        ),
    ]
