# Generated by Django 5.1.4 on 2025-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0002_alter_shopadsmodel_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadsmodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopadsmodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
