# Generated by Django 5.1.4 on 2025-04-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0003_shopadsmodel_latitude_shopadsmodel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadsmodel',
            name='ai_targeting_data',
            field=models.JSONField(blank=True, help_text='AI targeting metadata for this ad', null=True),
        ),
    ]
