# Generated by Django 5.1.4 on 2025-04-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0004_shopadsmodel_ai_targeting_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadsimpressionmodel',
            name='impression_type',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click')], default='view', help_text='Whether this was a view or a click', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopadsimpressionmodel',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='adsApp.shopadsmodel'),
        ),
    ]
