# Generated by Django 5.1.4 on 2025-04-09 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0005_shopadsimpressionmodel_impression_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadsimpressionmodel',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsApp.shopadsmodel'),
        ),
        migrations.AlterField(
            model_name='shopadsimpressionmodel',
            name='impression_type',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click')], default='view', max_length=10),
        ),
    ]
