# Generated by Django 5.1.4 on 2025-04-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0006_alter_shopadsimpressionmodel_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadsimpressionmodel',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='adsApp.shopadsmodel'),
        ),
        migrations.AlterField(
            model_name='shopadsimpressionmodel',
            name='impression_type',
            field=models.CharField(choices=[('click', 'Click'), ('view', 'View')], default='view', max_length=10),
        ),
    ]
