# Generated by Django 5.1.4 on 2025-04-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0007_alter_shopadsimpressionmodel_ad_and_more'),
        ('shopServiceApp', '0027_remove_serviceextendeddetailsmodel_process_step_templates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopadsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ads/cover'),
        ),
        migrations.AlterField(
            model_name='shopadsmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopServiceApp.shopservicedetailsmodel'),
        ),
        migrations.CreateModel(
            name='ShopAdsExtraFeaturesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_views', models.PositiveIntegerField(default=1000, help_text='Maximum views allowed for this ad')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Total views received')),
                ('target_age_min', models.PositiveIntegerField(default=18, help_text='Minimum target age')),
                ('target_age_max', models.PositiveIntegerField(default=65, help_text='Maximum target age')),
                ('device_type', models.CharField(blank=True, help_text="Optional: target device type (e.g., 'mobile' or 'desktop')", max_length=50, null=True)),
                ('schedule', models.CharField(blank=True, help_text="Ad schedule, e.g., '9am-5pm'", max_length=100, null=True)),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_features', to='adsApp.shopadsmodel')),
            ],
        ),
    ]
