# Generated by Django 5.1.4 on 2025-04-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsApp', '0009_shopadsmodel_budget_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='budget_spent',
        ),
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='creative_variants',
        ),
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='dynamic_adjustments',
        ),
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='frequency_cap',
        ),
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='ml_model_id',
        ),
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='ml_model_version',
        ),
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='time_window',
        ),
        migrations.RemoveField(
            model_name='shopadsmodel',
            name='user_segmentation_data',
        ),
    ]
