# Generated by Django 5.1.4 on 2025-04-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Sentiment analysis score', null=True),
        ),
    ]
