# Generated by Django 5.1.4 on 2024-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phoneOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=20)),
                ('otp_type', models.CharField(choices=[('available', 'Available'), ('driving', 'Driving'), ('busy', 'Busy'), ('idle', 'Idle')], max_length=20)),
            ],
        ),
    ]
