# Generated by Django 5.1.4 on 2024-12-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=20)),
                ('otp_type', models.CharField(choices=[('login', 'Login')], max_length=20)),
                ('otp_mode', models.CharField(choices=[('phone', 'Available'), ('email', 'Driving')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='phoneOTPModel',
        ),
    ]
