# Generated by Django 5.1.4 on 2024-12-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_sendotpmodel_delete_phoneotpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendotpmodel',
            name='otp_mode',
            field=models.CharField(choices=[('phone', 'Available'), ('email', 'Driving')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='sendotpmodel',
            name='otp_type',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Register'), ('reset_password', 'Reset password')], default='login', max_length=20),
        ),
    ]
