# Generated by Django 5.1.4 on 2025-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_sendotpmodel_otp_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendotpmodel',
            name='otp_mode',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='phone', max_length=20),
        ),
    ]
