# Generated by Django 5.1.4 on 2024-12-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_userprofilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_type',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
