# Generated by Django 5.1.4 on 2024-12-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_userprofilemodel_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='user_image',
            field=models.ImageField(default='', upload_to='images/userprofile'),
            preserve_default=False,
        ),
    ]
