# Generated by Django 5.1.4 on 2025-03-07 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
        ('shopApp', '0013_shopdetailsmodel_credits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroommodel',
            unique_together={('user', 'shop')},
        ),
    ]
