# Generated by Django 5.1.4 on 2025-04-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.FloatField(default=0.0)),
                ('total_specialists', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
