# Generated by Django 5.1.4 on 2025-04-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopDashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlog',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='average_salary',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='customer_retention_rate',
            field=models.FloatField(default=0.0, help_text='Percent of repeat customers'),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='date_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='estimated_wait_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='top_services',
            field=models.JSONField(blank=True, help_text='List of top services by bookings', null=True),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_ads_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_cancelled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_customers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_employees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_in_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_reels_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_waiting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
