# Generated by Django 5.1.4 on 2025-04-09 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0010_rename_company_registration_document_companydetailsmodel_registration_document_and_more'),
        ('shopApp', '0016_shopdetailsmodel_ai_personalization'),
        ('shopDashboardApp', '0002_dashboardlog_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_logs', to='companyApp.companydetailsmodel'),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_logs', to='shopApp.shopdetailsmodel'),
        ),
    ]
