# Generated by Django 5.1.4 on 2025-04-09 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0010_rename_company_registration_document_companydetailsmodel_registration_document_and_more'),
        ('shopApp', '0016_shopdetailsmodel_ai_personalization'),
        ('shopDashboardApp', '0003_dashboardlog_company_dashboardlog_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardlog',
            old_name='total_ads_clicks',
            new_name='total_ad_impressions',
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailsmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='customer_retention_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='estimated_wait_time',
            field=models.CharField(default='0 minutes', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Null for company‑wide snapshots', null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopdetailsmodel'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='top_services',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
