# Generated by Django 5.1.4 on 2025-04-09 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0014_alter_companydetailsmodel_options_and_more'),
        ('shopApp', '0016_shopdetailsmodel_ai_personalization'),
        ('shopDashboardApp', '0005_alter_dashboardlog_options_dashboardlog_branch_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardlog',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='dashboardlog',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='dashboardlog',
            name='date_range',
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_ad_clicks',
            field=models.IntegerField(default=0, help_text='Total ad clicks'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyApp.companydetailsmodel'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='estimated_wait_time',
            field=models.CharField(default='0 minutes', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopdetailsmodel'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='top_services',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_ad_impressions',
            field=models.IntegerField(default=0, help_text='Total ad impressions (views)'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_cancelled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_in_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_reels_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_specialists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_waiting',
            field=models.IntegerField(default=0),
        ),
    ]
