# Generated by Django 5.1.4 on 2025-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopDashboardApp', '0006_remove_dashboardlog_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlog',
            name='total_ad_viewers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_ad_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_ad_impressions',
            field=models.IntegerField(default=0),
        ),
    ]
