# Generated by Django 5.1.4 on 2025-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopDashboardApp', '0008_alter_dashboardlog_total_ad_clicks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_ad_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='total_ad_viewers',
            field=models.IntegerField(default=0),
        ),
    ]
