# Generated by Django 5.1.4 on 2025-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopDashboardApp', '0009_alter_dashboardlog_total_ad_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardlog',
            name='total_comments_per_reel',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_reels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_stories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardlog',
            name='total_story_likes',
            field=models.IntegerField(default=0),
        ),
    ]
