# Generated by Django 5.1.4 on 2025-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersdetailsmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True),
        ),
    ]
