# Generated by Django 5.1.4 on 2025-02-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersApp', '0002_alter_customersdetailsmodel_gender'),
        ('shopServiceApp', '0006_alter_servicebookingdetailsmodel_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='customer_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('new_customer', 'New Customer')], default='new_customer', max_length=20),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='preferred_services',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='shopServiceApp.shopservicecategorymodel'),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='profie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/customerprofile'),
        ),
    ]
