# Generated by Django 5.1.4 on 2025-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersApp', '0004_alter_customersdetailsmodel_user'),
        ('shopServiceApp', '0017_rename_is_availabe_shopservicedetailsmodel_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersdetailsmodel',
            name='preferred_services',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_customers', to='shopServiceApp.shopservicecategorymodel'),
        ),
    ]
