# Generated by Django 5.1.4 on 2025-04-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersApp', '0005_alter_customersdetailsmodel_preferred_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersdetailsmodel',
            name='birthDate',
        ),
        migrations.RemoveField(
            model_name='customersdetailsmodel',
            name='profie_photo',
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersdetailsmodel',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/customerprofile'),
        ),
    ]
