# Generated by Django 5.1.4 on 2025-02-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
