# Generated by Django 5.1.4 on 2025-01-27 08:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0005_alter_companydetailsmodel_user'),
        ('subscriptionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubscriptionPlansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('duration_days', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='SubscriptionPlansModels',
            new_name='UserSubscriptionPlansModels',
        ),
        migrations.CreateModel(
            name='CompanySubscriptionDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companyApp.companydetailsmodel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to='subscriptionApp.companysubscriptionplansmodel')),
            ],
        ),
    ]
