# Generated by Django 5.1.4 on 2025-03-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0002_companysubscriptionplansmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscriptionplansmodel',
            name='bookings_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscriptionplansmodel',
            name='branches_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscriptionplansmodel',
            name='employees_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscriptionplansmodel',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='companysubscriptionplansmodel',
            name='services_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscriptionplansmodel',
            name='specialists_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
