# Generated by Django 5.1.4 on 2025-03-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0003_companysubscriptionplansmodel_bookings_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('payment_type', models.CharField(choices=[('p', 'Payment'), ('u', 'Upgrade')], max_length=1)),
                ('payed_for', models.CharField(choices=[('s', 'Subscription'), ('ad', 'Ad Service'), ('b', 'Booking')], max_length=3)),
                ('creatd_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='companysubscriptiondetailsmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysubscriptiondetailsmodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='subscriptionApp.payment'),
        ),
    ]
