# Generated by Django 5.1.4 on 2025-04-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0004_payment_companysubscriptiondetailsmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='bill_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
