# Generated by Django 5.1.4 on 2025-04-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0006_companysubscriptiondetailsmodel_billing_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubscriptiondetailsmodel',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='companysubscriptionplansmodel',
            name='yearly_duration_days',
        ),
        migrations.RemoveField(
            model_name='companysubscriptionplansmodel',
            name='yearly_price',
        ),
    ]
