# Generated by Django 5.1.4 on 2025-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0007_remove_companysubscriptiondetailsmodel_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscriptiondetailsmodel',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='companysubscriptionplansmodel',
            name='yearly_duration_days',
            field=models.IntegerField(default=365),
        ),
        migrations.AddField(
            model_name='companysubscriptionplansmodel',
            name='yearly_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
