# Generated by Django 5.1.4 on 2025-04-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0008_companysubscriptiondetailsmodel_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
