# Generated by Django 5.1.4 on 2025-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0009_payment_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysubscriptiondetailsmodel',
            name='ai_churn_data',
            field=models.JSONField(blank=True, help_text='AI churn prediction data', null=True),
        ),
    ]
