# Generated by Django 5.1.4 on 2025-04-11 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('subscriptionApp', '0010_companysubscriptiondetailsmodel_ai_churn_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysubscriptiondetailsmodel',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='payment.payment'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
