# Generated by Django 5.1.4 on 2025-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0011_alter_companysubscriptiondetailsmodel_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptiondetailsmodel',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='usersubscriptiondetailsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='companysubscriptiondetailsmodel',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UserSubscriptionPlansModels',
        ),
        migrations.DeleteModel(
            name='UserSubscriptionDetailsModel',
        ),
    ]
