# Generated by Django 5.1.4 on 2025-01-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_shopspecialistdetailsmodel'),
        ('shopServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBookingDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('booking_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('discount_coupon', models.CharField(max_length=20)),
                ('canccellation_reason', models.TextField()),
                ('notes', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopServiceApp.shopservicedetailsmodel')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopspecialistdetailsmodel')),
            ],
        ),
    ]
