# Generated by Django 5.1.4 on 2025-01-27 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_shopspecialistdetailsmodel'),
        ('shopServiceApp', '0002_servicebookingdetailsmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBookingDiscountCouponsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed discount value', max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('max_usage', models.PositiveIntegerField(default=1, help_text='Number of times a coupon can be used')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicebookingdetailsmodel',
            name='booking_date_time',
        ),
        migrations.RemoveField(
            model_name='servicebookingdetailsmodel',
            name='canccellation_reason',
        ),
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final Amount', max_digits=100),
        ),
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bokkings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='discount_coupon',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bokkings', to='shopServiceApp.shopservicedetailsmodel'),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bokkings', to='shopApp.shopspecialistdetailsmodel'),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
