# Generated by Django 5.1.4 on 2025-01-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0003_servicebookingdiscountcouponsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='booking_date',
            field=models.DateField(default=None),
        ),
    ]
