# Generated by Django 5.1.4 on 2025-01-27 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0004_alter_servicebookingdetailsmodel_booking_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='booking_time',
            field=models.TimeField(default='10:30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, help_text='Final Amount', max_digits=100),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bokkings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
