# Generated by Django 5.1.4 on 2025-01-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0005_alter_servicebookingdetailsmodel_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final Amount', max_digits=100),
        ),
    ]
