# Generated by Django 5.1.4 on 2025-02-14 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersApp', '0003_customersdetailsmodel_address_and_more'),
        ('shopApp', '0009_alter_shopdetailsmodel_avatar_image_and_more'),
        ('shopServiceApp', '0006_alter_servicebookingdetailsmodel_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customersApp.customersdetailsmodel'),
        ),
        migrations.AddField(
            model_name='shopservicedetailsmodel',
            name='is_availabe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopservicedetailsmodel',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopservicedetailsmodel',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shopservicedetailsmodel',
            name='name_arabic',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='shopservicedetailsmodel',
            name='service_type',
            field=models.CharField(choices=[('in_shop', 'In Shop'), ('at_home', 'At Home'), ('both', 'Both')], default='in_shop', max_length=20),
        ),
        migrations.AddField(
            model_name='shopservicedetailsmodel',
            name='specialists',
            field=models.ManyToManyField(related_name='services_assigned', to='shopApp.shopspecialistdetailsmodel'),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bokkings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ShopServiceTimeSlotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time_slots', to='shopServiceApp.shopservicedetailsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='shopservicedetailsmodel',
            name='time_slots',
            field=models.ManyToManyField(blank=True, null=True, related_name='services', to='shopServiceApp.shopservicetimeslotmodel'),
        ),
    ]
