# Generated by Django 5.1.4 on 2025-02-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0008_remove_shopservicedetailsmodel_time_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopServiceGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='shop/service/gallery')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopServiceApp.shopservicedetailsmodel')),
            ],
        ),
    ]
