# Generated by Django 5.1.4 on 2025-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0009_shopservicegallerymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='booking_place',
            field=models.CharField(choices=[('in_shop', 'In Shop'), ('at_home', 'At Home'), ('both', 'Both')], default='in_shop', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
