# Generated by Django 5.1.4 on 2025-02-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0011_alter_shopspecialistdetailsmodel_employee'),
        ('shopServiceApp', '0010_servicebookingdetailsmodel_booking_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopservicedetailsmodel',
            name='shop',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shopApp.shopdetailsmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
