# Generated by Django 5.1.4 on 2025-02-21 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersApp', '0004_alter_customersdetailsmodel_user'),
        ('shopServiceApp', '0011_shopservicedetailsmodel_shop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopservicedetailsmodel',
            name='number_of_bookings',
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='customer',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='customersApp.customersdetailsmodel'),
            preserve_default=False,
        ),
    ]
