# Generated by Django 5.1.4 on 2025-02-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0012_specialisttypesmodel_and_more'),
        ('shopServiceApp', '0012_remove_shopservicedetailsmodel_number_of_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebookingdiscountcouponsmodel',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopApp.shopdetailsmodel'),
            preserve_default=False,
        ),
    ]
