# Generated by Django 5.1.4 on 2025-03-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0013_servicebookingdiscountcouponsmodel_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopservicegallerymodel',
            name='file',
            field=models.FileField(default='', upload_to='shop/service/gallery'),
            preserve_default=False,
        ),
    ]
