# Generated by Django 5.1.4 on 2025-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0014_alter_shopservicegallerymodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebookingdiscountcouponsmodel',
            name='apply_to_all_services',
            field=models.BooleanField(default=False, help_text='Check if this discount applies to all services in the shop.'),
        ),
        migrations.AddField(
            model_name='servicebookingdiscountcouponsmodel',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Select specific services if the discount does not apply to all services.', to='shopServiceApp.shopservicedetailsmodel'),
        ),
    ]
