# Generated by Django 5.1.4 on 2025-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0015_servicebookingdiscountcouponsmodel_apply_to_all_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebookingdetailsmodel',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1 to 5', null=True),
        ),
    ]
