# Generated by Django 5.1.4 on 2025-04-10 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0017_rename_is_availabe_shopservicedetailsmodel_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicebookingdetailsmodel',
            options={'verbose_name': 'Service Booking Detail', 'verbose_name_plural': 'Service Booking Details'},
        ),
        migrations.AlterModelOptions(
            name='servicebookingdiscountcouponsmodel',
            options={'verbose_name': 'Service Booking Discount Coupon', 'verbose_name_plural': 'Service Booking Discount Coupons'},
        ),
        migrations.AlterModelOptions(
            name='shopservicecategorymodel',
            options={'verbose_name': 'Shop Service Category', 'verbose_name_plural': 'Shop Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='shopservicedetailsmodel',
            options={'verbose_name': 'Shop Service Detail', 'verbose_name_plural': 'Shop Service Details'},
        ),
        migrations.AlterModelOptions(
            name='shopservicegallerymodel',
            options={'verbose_name': 'Shop Service Gallery Item', 'verbose_name_plural': 'Shop Service Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='shopservicetimeslotmodel',
            options={'verbose_name': 'Service Time Slot', 'verbose_name_plural': 'Service Time Slots'},
        ),
        migrations.CreateModel(
            name='ServiceExtendedDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_description', models.TextField(blank=True, help_text='A detailed description of the service.', null=True, verbose_name='Detailed Description')),
                ('faq', models.TextField(blank=True, help_text='Frequently asked questions about the service.', null=True, verbose_name='FAQ')),
                ('benefits', models.TextField(blank=True, help_text='Key benefits for the customer.', null=True, verbose_name='Benefits')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Any additional cost for the service details', max_digits=10, verbose_name='Additional Price')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_details', to='shopServiceApp.shopservicedetailsmodel', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Extended Detail',
                'verbose_name_plural': 'Service Extended Details',
            },
        ),
    ]
