# Generated by Django 5.1.4 on 2025-04-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0018_alter_servicebookingdetailsmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceextendeddetailsmodel',
            name='additional_price',
        ),
        migrations.AddField(
            model_name='serviceextendeddetailsmodel',
            name='aftercare',
            field=models.TextField(blank=True, help_text='Aftercare tips for this service.', null=True, verbose_name='Aftercare Tips'),
        ),
    ]
