# Generated by Django 5.1.4 on 2025-04-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0020_serviceprocessstep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProcessStep',
        ),
    ]
