# Generated by Django 5.1.4 on 2025-04-10 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0021_delete_serviceprocessstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='The sequence number for this step')),
                ('title', models.CharField(help_text='Title of the step', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the step', null=True, upload_to='service_process_steps/')),
                ('description', models.TextField(blank=True, help_text='Description of this process step')),
                ('extended_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='shopServiceApp.serviceextendeddetailsmodel', verbose_name='Extended Details')),
            ],
            options={
                'verbose_name': 'Service Process Step',
                'verbose_name_plural': 'Service Process Steps',
                'ordering': ['step_number'],
            },
        ),
    ]
