# Generated by Django 5.1.4 on 2025-04-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0022_serviceprocessstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceextendeddetailsmodel',
            name='aftercare',
        ),
        migrations.RemoveField(
            model_name='serviceextendeddetailsmodel',
            name='benefits',
        ),
        migrations.AddField(
            model_name='serviceextendeddetailsmodel',
            name='overview_image',
            field=models.ImageField(blank=True, help_text='Overview image for the service', null=True, upload_to='service_overview/', verbose_name='Overview Image'),
        ),
        migrations.AddField(
            model_name='serviceextendeddetailsmodel',
            name='overview_title',
            field=models.CharField(blank=True, help_text='Overview title for the service', max_length=200, null=True, verbose_name='Overview Title'),
        ),
        migrations.CreateModel(
            name='ServiceAftercareTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_text', models.CharField(max_length=300)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('extended_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aftercare_tips', to='shopServiceApp.serviceextendeddetailsmodel', verbose_name='Extended Details')),
            ],
            options={
                'verbose_name': 'Service Aftercare Tip',
                'verbose_name_plural': 'Service Aftercare Tips',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_text', models.CharField(max_length=300)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('extended_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='shopServiceApp.serviceextendeddetailsmodel', verbose_name='Extended Details')),
            ],
            options={
                'verbose_name': 'Service Benefit',
                'verbose_name_plural': 'Service Benefits',
                'ordering': ['order_index'],
            },
        ),
    ]
