# Generated by Django 5.1.4 on 2025-04-10 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0017_alter_shopdetailsmodel_options_and_more'),
        ('shopServiceApp', '0025_remove_serviceextendeddetailsmodel_faq_servicefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProcessStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the process step template', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description for the template')),
                ('image', models.ImageField(blank=True, help_text='Optional image for the template', null=True, upload_to='process_step_templates/')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order index for display in the template library')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('shop', models.ForeignKey(help_text='The shop that owns this template', on_delete=django.db.models.deletion.CASCADE, related_name='process_step_templates', to='shopApp.shopdetailsmodel')),
            ],
            options={
                'verbose_name': 'Service Process Step Template',
                'verbose_name_plural': 'Service Process Step Templates',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='serviceextendeddetailsmodel',
            name='process_step_templates',
            field=models.ManyToManyField(blank=True, help_text='Select process step templates to apply to this service.', related_name='extended_details_templates', to='shopServiceApp.serviceprocesssteptemplate'),
        ),
    ]
