# Generated by Django 5.1.4 on 2025-04-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0026_serviceprocesssteptemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceextendeddetailsmodel',
            name='process_step_templates',
        ),
        migrations.AlterModelOptions(
            name='serviceprocessstep',
            options={'ordering': ['order_index'], 'verbose_name': 'Service Process Step', 'verbose_name_plural': 'Service Process Steps'},
        ),
        migrations.RemoveField(
            model_name='serviceprocessstep',
            name='step_number',
        ),
        migrations.AddField(
            model_name='serviceprocessstep',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text='Order index for display'),
        ),
        migrations.DeleteModel(
            name='ServiceProcessStepTemplate',
        ),
    ]
