# Generated by Django 5.1.4 on 2025-04-15 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0027_remove_serviceextendeddetailsmodel_process_step_templates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='shopservicetimeslotmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
