# Generated by Django 5.1.4 on 2025-04-18 13:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0028_alter_shopservicedetailsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceaftercaretip',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='servicebenefit',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='servicebookingdetailsmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicebookingdiscountcouponsmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceextendeddetailsmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicefaq',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='serviceoverview',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='serviceprocessstep',
            options={'ordering': ['order_index']},
        ),
        migrations.AlterModelOptions(
            name='shopservicecategorymodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shopservicedetailsmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shopservicegallerymodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shopservicetimeslotmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='serviceaftercaretip',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aftercare_tips', to='shopServiceApp.serviceextendeddetailsmodel'),
        ),
        migrations.AlterField(
            model_name='servicebenefit',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='shopServiceApp.serviceextendeddetailsmodel'),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='fraud_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceextendeddetailsmodel',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceextendeddetailsmodel',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_details', to='shopServiceApp.shopservicedetailsmodel'),
        ),
        migrations.AlterField(
            model_name='serviceextendeddetailsmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='shopServiceApp.serviceextendeddetailsmodel'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='question',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='shopServiceApp.serviceextendeddetailsmodel'),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_overview/'),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='shopServiceApp.serviceextendeddetailsmodel'),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_process_steps/'),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='shopservicecategorymodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='shopservicecategorymodel',
            name='forecast_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='forecast_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
