# Generated by Django 5.1.4 on 2025-04-18 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0029_alter_serviceaftercaretip_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceaftercaretip',
            options={'ordering': ['order_index'], 'verbose_name': 'Service Aftercare Tip', 'verbose_name_plural': 'Service Aftercare Tips'},
        ),
        migrations.AlterModelOptions(
            name='servicebenefit',
            options={'ordering': ['order_index'], 'verbose_name': 'Service Benefit', 'verbose_name_plural': 'Service Benefits'},
        ),
        migrations.AlterModelOptions(
            name='servicebookingdetailsmodel',
            options={'verbose_name': 'Service Booking Detail', 'verbose_name_plural': 'Service Booking Details'},
        ),
        migrations.AlterModelOptions(
            name='servicebookingdiscountcouponsmodel',
            options={'verbose_name': 'Service Booking Discount Coupon', 'verbose_name_plural': 'Service Booking Discount Coupons'},
        ),
        migrations.AlterModelOptions(
            name='serviceextendeddetailsmodel',
            options={'verbose_name': 'Service Extended Detail', 'verbose_name_plural': 'Service Extended Details'},
        ),
        migrations.AlterModelOptions(
            name='servicefaq',
            options={'ordering': ['order_index'], 'verbose_name': 'Service FAQ', 'verbose_name_plural': 'Service FAQs'},
        ),
        migrations.AlterModelOptions(
            name='serviceoverview',
            options={'ordering': ['order_index'], 'verbose_name': 'Service Overview', 'verbose_name_plural': 'Service Overviews'},
        ),
        migrations.AlterModelOptions(
            name='serviceprocessstep',
            options={'ordering': ['order_index'], 'verbose_name': 'Service Process Step', 'verbose_name_plural': 'Service Process Steps'},
        ),
        migrations.AlterModelOptions(
            name='shopservicecategorymodel',
            options={'verbose_name': 'Shop Service Category', 'verbose_name_plural': 'Shop Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='shopservicedetailsmodel',
            options={'verbose_name': 'Shop Service Detail', 'verbose_name_plural': 'Shop Service Details'},
        ),
        migrations.AlterModelOptions(
            name='shopservicegallerymodel',
            options={'verbose_name': 'Shop Service Gallery Item', 'verbose_name_plural': 'Shop Service Gallery Items'},
        ),
        migrations.AlterModelOptions(
            name='shopservicetimeslotmodel',
            options={'verbose_name': 'Service Time Slot', 'verbose_name_plural': 'Service Time Slots'},
        ),
        migrations.AlterField(
            model_name='serviceaftercaretip',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aftercare_tips', to='shopServiceApp.serviceextendeddetailsmodel', verbose_name='Extended Details'),
        ),
        migrations.AlterField(
            model_name='servicebenefit',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='shopServiceApp.serviceextendeddetailsmodel', verbose_name='Extended Details'),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='servicebookingdetailsmodel',
            name='fraud_flag',
            field=models.BooleanField(default=False, help_text='Flag if booking is potentially fraudulent'),
        ),
        migrations.AlterField(
            model_name='serviceextendeddetailsmodel',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='A detailed description of the service.', null=True, verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='serviceextendeddetailsmodel',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_details', to='shopServiceApp.shopservicedetailsmodel', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='serviceextendeddetailsmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='answer',
            field=models.TextField(help_text='The answer to the FAQ question'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='shopServiceApp.serviceextendeddetailsmodel', verbose_name='Extended Details'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text='Order index for display'),
        ),
        migrations.AlterField(
            model_name='servicefaq',
            name='question',
            field=models.CharField(help_text='The FAQ question', max_length=300),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the overview item'),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='shopServiceApp.serviceextendeddetailsmodel', verbose_name='Extended Details'),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the overview item', null=True, upload_to='service_overview/'),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text='Order index for display'),
        ),
        migrations.AlterField(
            model_name='serviceoverview',
            name='title',
            field=models.CharField(help_text='Title of the overview item', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this process step'),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='extended_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='shopServiceApp.serviceextendeddetailsmodel', verbose_name='Extended Details'),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the step', null=True, upload_to='service_process_steps/'),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='order_index',
            field=models.PositiveIntegerField(default=0, help_text='Order index for display'),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='title',
            field=models.CharField(help_text='Title of the process step', max_length=200),
        ),
        migrations.AlterField(
            model_name='shopservicecategorymodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='shopservicecategorymodel',
            name='forecast_data',
            field=models.JSONField(blank=True, help_text='AI forecast metadata for this category', null=True),
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='forecast_data',
            field=models.JSONField(blank=True, help_text='AI forecast metadata for this service', null=True),
        ),
    ]
