# Generated by Django 5.1.4 on 2025-04-18 13:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0030_alter_serviceaftercaretip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopservicecategorymodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='shopservicecategorymodel',
            name='forecast_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='forecast_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
