# Generated by Django 5.1.4 on 2025-04-18 13:56

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopServiceApp', '0031_alter_shopservicecategorymodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopservicecategorymodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='shopservicecategorymodel',
            name='forecast_data',
            field=models.JSONField(blank=True, help_text='AI forecast metadata for this category', null=True),
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Duration of service'),
        ),
        migrations.AlterField(
            model_name='shopservicedetailsmodel',
            name='forecast_data',
            field=models.JSONField(blank=True, help_text='AI forecast metadata for this service', null=True),
        ),
    ]
