# Generated by Django 5.1.4 on 2025-04-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customersApp', '0005_alter_customersdetailsmodel_preferred_services'),
        ('shopApp', '0020_alter_shopdetailsmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_follows', to='customersApp.customersdetailsmodel')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='shopApp.shopdetailsmodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'shop')},
            },
        ),
    ]
