name: "Report  Linting"

on: 
    workflow_dispatch:
    push:
        branches: [feature/**]
    pull_request:
        branches: [feature/**]

jobs:
    linting:
        runs-on : ubuntu-latest
        steps:
            - name: Checkout code 
              uses: actions/checkout@v2
            
            - name: Set up Python 
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
            - name : install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name : Run Linting
              run: |
                pip install flake8
                flake8 --max-line-length=120 --ignore=E501,E203,E266,W503 reportAnlyticsApp/views.py
               
        